import AndroidKit
import ArgumentParser
import Foundation

struct EnvCommand: AsyncParsableCommand {
    static let configuration = CommandConfiguration(
        commandName: "env",
        abstract: "Print shell exports for ANDROID_HOME, JAVA_HOME and PATH.",
        discussion: """
        Append to your shell profile with, for example:
          andyman env >> ~/.zshrc
        """
    )

    @OptionGroup var options: GlobalOptions

    @Option(help: "Shell syntax to print. Defaults to the shell in $SHELL.")
    var shell: ShellExports.Shell?

    struct Payload: Encodable {
        var schemaVersion = Output.schemaVersion
        var shell: ShellExports.Shell
        var profile: String
        var sdkPath: String
        var javaHome: String?
        var lines: [String]
    }

    func run() async throws {
        let environment = CommandContext(options).environment
        let settings = SharedPreferences()

        let sdk = SDKLocator().resolve(flag: options.sdk, settings: settings.sdkPathOverride, environment: environment)
        guard sdk.isValid, let location = sdk.location else {
            throw CLIError.sdkNotFound(
                "No usable Android SDK found.",
                hint: "Run `andyman doctor` for details, or pass --sdk <path>."
            )
        }

        let locator = JavaLocator()
        let java = locator.resolve(
            settings: settings.javaHomeOverride,
            environment: environment,
            installations: await locator.installations()
        ).selected

        let shell = shell ?? ShellExports.Shell(shellPath: environment["SHELL"])
        let lines = ShellExports.lines(sdkPath: location.path, java: java, shell: shell)

        if options.json {
            try Output.json(Payload(
                shell: shell,
                profile: shell.profilePath,
                sdkPath: location.path,
                javaHome: java?.home,
                lines: lines
            ))
        } else {
            Output.line("# Android development (generated by andyman)")
            lines.forEach { Output.line($0) }
            if java == nil {
                Output.errorLine("warning: no JDK \(JavaLocator.minimumMajorVersion)+ found, so JAVA_HOME was left out.")
            }
        }
    }
}

extension ShellExports.Shell: ExpressibleByArgument {}
