import AndroidKit
import ArgumentParser
import Foundation

struct SkillCommand: AsyncParsableCommand {
    static let configuration = CommandConfiguration(
        commandName: "skill",
        abstract: "Print or install the agent skill that teaches coding agents to use andyman.",
        discussion: """
        The skill (SKILL.md, Agent Skills format) is generated by this version of andyman. \
        Agents: \(AgentSkills.targets().map(\.id).joined(separator: ", ")). `agents` is the shared \
        ~/.agents/skills folder several agents read.
        """,
        subcommands: [Print.self, Status.self, Install.self, Uninstall.self, AgentsSnippet.self]
    )

    struct AgentOptions: ParsableArguments {
        @Option(name: .customLong("agent"), help: "Agent ID (repeatable). Defaults to every agent found on this Mac.")
        var agents: [String] = []
        @Option(help: ArgumentHelp("Install into this project instead of your user folders.", valueName: "path"))
        var project: String?

        func selected() throws -> [AgentTarget] {
            let all = AgentSkills.targets()
            guard !agents.isEmpty else {
                // In a project, default to Claude Code's folder and the shared one.
                if project != nil { return all.filter { ["claude", "agents"].contains($0.id) } }
                return all.filter(\.isDetected)
            }
            return try agents.map { id in
                guard let target = all.first(where: { $0.id == id }) else {
                    throw CLIError(code: "unknown_agent", message: "There's no agent called \(id).", hint: "Use one of: \(all.map(\.id).joined(separator: ", ")).", exitStatus: .usage)
                }
                return target
            }
        }

        func folder(for target: AgentTarget) -> URL {
            if let project {
                return AgentSkills.projectSkillsFolder(target, project: URL(fileURLWithPath: ShellEnvironment.expandTilde(project), isDirectory: true).standardizedFileURL)
            }
            return AgentSkills.userSkillsFolder(target)
        }
    }

    struct Entry: Encodable {
        var agent: String
        var name: String
        var detected: Bool
        var path: String
        var state: SkillInstallState
    }

    static var content: String { SkillDocument.render(executable: SkillDocument.executablePath) }

    struct Print: AsyncParsableCommand {
        static let configuration = CommandConfiguration(abstract: "Print the skill (SKILL.md).")

        @OptionGroup var options: GlobalOptions

        func run() async throws {
            let content = SkillCommand.content
            if options.json {
                struct Payload: Encodable {
                    var schemaVersion = Output.schemaVersion
                    var name: String
                    var version: String
                    var content: String
                }
                try Output.json(Payload(name: AgentSkills.skillName, version: AgentSkills.frontmatterVersion(content) ?? "", content: content))
            } else {
                FileHandle.standardOutput.write(Data(content.utf8))
            }
        }
    }

    struct Status: AsyncParsableCommand {
        static let configuration = CommandConfiguration(abstract: "Show which agents have the skill and whether it's up to date.")

        @OptionGroup var options: GlobalOptions
        @Option(help: ArgumentHelp("Check this project's skill folders.", valueName: "path")) var project: String?

        func run() async throws {
            let content = SkillCommand.content
            let projectURL = project.map { URL(fileURLWithPath: ShellEnvironment.expandTilde($0), isDirectory: true).standardizedFileURL }
            let entries = AgentSkills.targets().map { target in
                let folder = projectURL.map { AgentSkills.projectSkillsFolder(target, project: $0) } ?? AgentSkills.userSkillsFolder(target)
                return Entry(
                    agent: target.id, name: target.name, detected: target.isDetected,
                    path: AgentSkills.skillFile(in: folder).path, state: AgentSkills.state(of: folder, current: content)
                )
            }
            if options.json {
                struct Payload: Encodable {
                    var schemaVersion = Output.schemaVersion
                    var version: String
                    var agents: [Entry]
                }
                try Output.json(Payload(version: AgentSkills.frontmatterVersion(content) ?? "", agents: entries))
                return
            }
            Output.table(header: ["AGENT", "FOUND", "SKILL", "PATH"], rows: entries.map {
                [$0.agent, $0.detected ? "yes" : "no", $0.state.rawValue.replacingOccurrences(of: "_", with: " "), $0.path]
            })
        }
    }

    struct Install: AsyncParsableCommand {
        static let configuration = CommandConfiguration(
            abstract: "Install (or update) the skill for coding agents.",
            discussion: "Without --agent, installs for every agent found on this Mac. Skips a different skill with the same name."
        )

        @OptionGroup var options: GlobalOptions
        @OptionGroup var agentOptions: AgentOptions

        func run() async throws {
            let content = SkillCommand.content
            let targets = try agentOptions.selected()
            guard !targets.isEmpty else {
                throw CLIError(code: "no_agents", message: "No coding agents found on this Mac.", hint: "Pass --agent (e.g. --agent agents for ~/.agents/skills).", exitStatus: .notFound)
            }
            var installed: [String] = []
            var skipped: [String] = []
            for target in targets {
                do {
                    let file = try AgentSkills.install(content, into: agentOptions.folder(for: target))
                    installed.append(file.path)
                } catch let error as AgentSkillError {
                    if !options.json { Output.errorLine("Skipped \(target.name): \(error.localizedDescription)") }
                    skipped.append(target.id)
                }
            }
            try Output.result(
                json: options.json,
                message: installed.isEmpty ? "Nothing installed." : "Installed the skill:\n" + installed.map { "  \($0)" }.joined(separator: "\n"),
                fields: ["installed": installed, "skipped": skipped, "version": AgentSkills.frontmatterVersion(content) ?? ""]
            )
        }
    }

    struct Uninstall: AsyncParsableCommand {
        static let configuration = CommandConfiguration(abstract: "Remove the skill from coding agents.")

        @OptionGroup var options: GlobalOptions
        @OptionGroup var agentOptions: AgentOptions

        func run() async throws {
            var removed: [String] = []
            for target in try agentOptions.selected() {
                let folder = agentOptions.folder(for: target)
                guard AgentSkills.state(of: folder, current: "") != .notInstalled else { continue }
                do {
                    try AgentSkills.uninstall(from: folder)
                    removed.append(AgentSkills.skillFile(in: folder).path)
                } catch {
                    if !options.json { Output.errorLine("Skipped \(target.name): \(error.localizedDescription)") }
                }
            }
            try Output.result(json: options.json, message: removed.isEmpty ? "The skill wasn't installed." : "Removed \(removed.count) cop\(removed.count == 1 ? "y" : "ies").", fields: ["removed": removed])
        }
    }

    struct AgentsSnippet: AsyncParsableCommand {
        static let configuration = CommandConfiguration(
            commandName: "agents-md",
            abstract: "Print a short AGENTS.md / CLAUDE.md section for agents that don't load skills."
        )

        @OptionGroup var options: GlobalOptions

        func run() async throws {
            let snippet = SkillDocument.agentsSnippet(executable: SkillDocument.executablePath)
            if options.json {
                try Output.result(json: true, message: "AGENTS.md snippet", fields: ["content": snippet])
            } else {
                Output.line(snippet)
            }
        }
    }
}
